---
name: DB Version Management

on:
  workflow_dispatch:
  workflow_call:

jobs:
  update-db-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install yq
        run: sudo apt-get install -y yq

      - name: Check if PR already bumped
        id: check_bump
        run: |
          PR_NUM="${{ github.event.pull_request.number }}"
          if yq -e ".versions[] | select(.pr == ${PR_NUM})" .db-versions.yml > /dev/null 2>&1; then
            echo "already_bumped=true" >> $GITHUB_OUTPUT
          else
            echo "already_bumped=false" >> $GITHUB_OUTPUT
          fi

      - name: Configure Git
        if: steps.check_bump.outputs.already_bumped == 'false'
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Update DB Version
        if: steps.check_bump.outputs.already_bumped == 'false'
        run: |
          ./scripts/update-db-version.sh "${{ github.event.pull_request.number }}"

      - name: Commit and Push
        if: steps.check_bump.outputs.already_bumped == 'false'
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .db-versions.toml
            git commit -m "chore: bump db version"
            git push origin HEAD
          fi
